### ISSUE TITLE
Changelogs needs dates so I can know if I am out of date or not

### ISSUE THREAD

**Issue by AlexWFreitas** [dodekeract/manta-config-engine#10]
Same for the config file itself, the one I used doesn't tell what version I was in.

**Comment by FlorianWendelborn** [comment]
Good and somewhat obvious idea. Wonder why I didn't already do it. Will try do add this today.

As a workaround you can use the [Blame view](https://github.com/dodekeract/manta-config-engine/blame/master/documentation/CHANGELOG.md).

**Comment by FlorianWendelborn** [comment]
Fixed via ef6fafe67b679e88ab2f061d90472117072cf871 and dodekeract/manta-config-engine-app@2f2c85957c312b524c6290dea8937c0339e01509
