### ISSUE TITLE
Fix or remove invalid settings after spring cleaning update

### ISSUE THREAD

**Issue by crimsonvspurple** [dodekeract/manta-config-engine#12]
There are quite a few settings that do not work anymore.
1. Either these should be fixed
2. Or these should be removed from Manta.

For example:
Auto attack is not 2 bools anymore. It uses
dota_player_units_auto_attack_mode[0] = 0 | 1 | 2
where 0 is never; 1 is after spell; 2 is always.

There's new option for summoned units: dota_summoned_units_auto_attack_mode[0] and more.

In my opinion, these should be removed as these can easily be configured from in game options. In game options are easy to configure and synced nicely. I think focusing on augmenting that instead of completely replacing is a better approach.

**Comment by FlorianWendelborn** [comment]
I don't agree that settings available in the in game settings should be removed. I personally really like that wherever I am, I just have to copy in my autoexec and everything works as I want it to work. That's one of the things Manta attempts to solve. The old settings however, should and will be removed.

**Comment by crimsonvspurple** [comment]
I don't see how having settings in autoexec for things that are easily accessible on options (and _is synced using steam cloud_) helps any way except increasing complication. Anyways, these would need fix if you want to keep them.

**Comment by FlorianWendelborn** [comment]
What about multiple accounts? What about quickly playing a game on a friend's computer? What if your family can only afford 1 PC for two kids?

**Comment by FlorianWendelborn** [comment]
I mean there is a hybrid solution. They could be placed in a different tab. That'd be okay IMHO.

**Comment by JSamir** [comment]
Personally I don't want to ever touch in game settings if possible. 

Besides the portability of the autoexec, Dota forgets my settings on a regular basis. 

+1 for keeping as much settings in the config as possible.

**Comment by glebmachine** [comment]
@dodekeract  Looks like config working again!!!!

**Comment by glebmachine** [comment]
Damn, sorry, hear enabling sound, and checked it in hero demo mode(((

**Comment by FlorianWendelborn** [comment]
@glebmachine :cry:

**Comment by glebmachine** [comment]
Sorry mate, i can't describe my frustration about dis : ////
