### ISSUE TITLE
Suggestion for non-default save location

### ISSUE THREAD

**Issue by gwerbin** [dodekeract/manta-config-engine#2]
How hard would it be to add an option like `-o path/to/alternate/script/location` to the CLI interface? I'm on a Mac so obviously `C:\...` isn't the right place to save on my machine.

**Comment by FlorianWendelborn** [comment]
Should be easily possible. However it would be good if the CLI detects the operating system and defaults to the default path for that system. I have no idea where that would be on a mac though.

**Comment by gwerbin** [comment]
I use a Mac so I'll check when I get to my computer. Alternatively I'd be fine if I could just send it to std output à la `curl`

**Comment by gwerbin** [comment]
It's `~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/cfg`. Note that Mac systems have both `~/Library` and `/Library`.

**Comment by FlorianWendelborn** [comment]
Should be able to implement this tomorrow, thanks.
