### ISSUE TITLE
Support CRLF.

### ISSUE THREAD

**Issue by FlorianWendelborn** [dodekeract/manta-config-engine#9]
[via Reddit](https://www.reddit.com/r/DotA2/comments/45lbum/advanced_autoexec_generator_update/czyudlf)

Oh, Windows/Notepad.

**Comment by Sembrani** [comment]
Since git automatically changes them in the project;
https://help.github.com/articles/dealing-with-line-endings/

I suspect changing the source files may help since generating the files comes from snippets already created I assume.

**Comment by FlorianWendelborn** [comment]
The issue is, that Manta compiles JSON to autoexec manually. Every time it inserts a line **it just assumes it's only a LF**. Bad text editors like notepad don't recognize that and therefore fuck up formatting. It has to be changed in the internals of the engine, since Manta doesn't consist of autoexec snippets, but rather of an autoexec generator.
